services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: certifier
  MYSQL_ROOT_PASSWORD: root

stages:
  - build
  - assemble
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean package -Pprod
  tags:
    - docker
    - shared
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - target/*.war
    expire_in: 1 week

docker-build-app:
  stage: assemble
  image: docker:latest
  variables:
    IMAGE_TAG : $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  services:
    - docker:dind
  script:
    - docker info
    - docker build -t $IMAGE_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG
    
  tags:
    - docker
    - shared

docker-build-sqlscript:
  stage: assemble
  image: docker:latest
  variables:
    IMAGE_TAG : $CI_REGISTRY_IMAGE:sqlscript
  services:
    - docker:dind
  script:
    - cd src/main/resources/sql/
    - docker info
    - docker build -t $IMAGE_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG

  tags:
    - docker
    - shared
