stages:

  - build
  - assemble
  - deploy

build:
  stage: build
  image: maven:latest
  services:
    - velmuruganv/mysql:latest
  script:
    - mvn clean test jacoco:report package -Pprod
  tags:
    - docker
    - shared
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID}"
    paths:
      - target/*.war
      - target/site/
    expire_in: 1 week

docker-build-app:
  stage: assemble
  image: docker:latest
  variables:
    IMAGE_TAG : $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  services:
    - docker:dind
  script:
    - docker info
    - docker build -t $IMAGE_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG
    
  tags:
    - docker
    - shared

docker-build-sqlscript:
  stage: assemble
  image: docker:latest
  variables:
    IMAGE_TAG : $CI_REGISTRY_IMAGE:sqlscript
  services:
    - docker:dind
  script:
    - cd src/main/resources/sql/
    - docker info
    - docker build -t $IMAGE_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG

  tags:
    - docker
    - shared

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv target/site/jacoco public/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID}_pages"
    paths:
      - public
    expire_in: 30 days
  only:
    - master
 
deploy_local_vm:
  stage: deploy
  script:    
    - curl -s https://raw.githubusercontent.com/velmuruganvelayutham/shell-scripts/master/deploy.sh | bash -s
  environment:
    name: local-vm
    url: http://dev.mock-labs.com
  only:
    - master
  when: manual
  tags:
    - shell-osboxes

