image: docker:latest

services:
  - mysql:latest
  - docker:dind

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: certifier
  MYSQL_ROOT_PASSWORD: root

stages:
  - build
  - assemble
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean package -Pprod
  tags:
    - docker
    - shared

docker-build:
  stage: assemble
  image: docker:latest
  script:
    - docker info
  tags:
    - docker
    - shared
