image: docker:latest

services:
  - mysql:latest
  - docker:dind

before_script:
  - docker info

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: certifier
  MYSQL_ROOT_PASSWORD: root

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  script:
    - mvn clean package -Pprod
  tags:
    - docker
    - shared
