services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: certifier
  MYSQL_ROOT_PASSWORD: root

stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean package -Pprod
  tags:
    - docker
