version: '2'

volumes:
    uploads:
        driver: local
  
services:
    sqlscript:
        build:
            context: src/main/resources/sql/
            dockerfile: Dockerfile
    tomcat:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - mysql
        ports:
            - "80:8080"

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tradeshow
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=root
        ports:
            - "3306:3306"
        volumes_from:
            - sqlscript

